import type { User } from "@/types";

export const users: User[] = [
  {
    id: "usr_001",
    name: "Priya Sharma",
    email: "priya.sharma@techcorp.in",
    role: "admin",
    status: "active",
    country: "India",
    joinedAt: "2023-03-15T10:30:00Z",
  },
  {
    id: "usr_002",
    name: "Jean-Pierre Dubois",
    email: "jp.dubois@entreprise.fr",
    role: "manager",
    status: "active",
    country: "France",
    joinedAt: "2023-05-22T14:45:00Z",
  },
  {
    id: "usr_003",
    name: "Carlos Rodriguez",
    email: "carlos.r@startup.es",
    role: "user",
    status: "active",
    country: "Spain",
    joinedAt: "2023-07-08T09:15:00Z",
  },
  {
    id: "usr_004",
    name: "Emily Chen",
    email: "emily.chen@globaltech.com",
    role: "admin",
    status: "active",
    country: "USA",
    joinedAt: "2023-01-10T16:20:00Z",
  },
  {
    id: "usr_005",
    name: "Hans Mueller",
    email: "h.mueller@firma.de",
    role: "manager",
    status: "active",
    country: "Germany",
    joinedAt: "2023-04-18T11:00:00Z",
  },
  {
    id: "usr_006",
    name: "Amit Patel",
    email: "amit.patel@innovation.in",
    role: "user",
    status: "suspended",
    country: "India",
    joinedAt: "2023-08-25T08:30:00Z",
  },
  {
    id: "usr_007",
    name: "Sophie Martin",
    email: "sophie.m@agence.fr",
    role: "user",
    status: "active",
    country: "France",
    joinedAt: "2023-09-12T13:45:00Z",
  },
  {
    id: "usr_008",
    name: "Maria Garcia",
    email: "maria.garcia@empresa.es",
    role: "manager",
    status: "active",
    country: "Spain",
    joinedAt: "2023-06-30T10:00:00Z",
  },
  {
    id: "usr_009",
    name: "Michael Johnson",
    email: "m.johnson@solutions.com",
    role: "user",
    status: "active",
    country: "USA",
    joinedAt: "2023-10-05T15:30:00Z",
  },
  {
    id: "usr_010",
    name: "Klaus Weber",
    email: "k.weber@technik.de",
    role: "user",
    status: "suspended",
    country: "Germany",
    joinedAt: "2023-02-28T12:15:00Z",
  },
  {
    id: "usr_011",
    name: "Rahul Verma",
    email: "rahul.v@digital.in",
    role: "manager",
    status: "active",
    country: "India",
    joinedAt: "2023-11-14T09:00:00Z",
  },
  {
    id: "usr_012",
    name: "Claire Lefevre",
    email: "c.lefevre@conseil.fr",
    role: "user",
    status: "active",
    country: "France",
    joinedAt: "2023-12-01T14:00:00Z",
  },
  {
    id: "usr_013",
    name: "Antonio Fernandez",
    email: "a.fernandez@grupo.es",
    role: "admin",
    status: "active",
    country: "Spain",
    joinedAt: "2023-04-25T11:30:00Z",
  },
  {
    id: "usr_014",
    name: "Sarah Williams",
    email: "s.williams@corp.com",
    role: "user",
    status: "active",
    country: "USA",
    joinedAt: "2023-07-19T16:45:00Z",
  },
  {
    id: "usr_015",
    name: "Thomas Schneider",
    email: "t.schneider@gmbh.de",
    role: "manager",
    status: "active",
    country: "Germany",
    joinedAt: "2023-08-08T10:30:00Z",
  },
];
