replexica:
  image: $CI_REGISTRY_IMAGE:latest
  variables:
    GITLAB_TOKEN: $GITLAB_TOKEN
    GITLAB_BASE_BRANCH: $CI_DEFAULT_BRANCH
    GITLAB_REPOSITORY_OWNER: $CI_PROJECT_NAMESPACE
    GITLAB_REPOSITORY_NAME: $CI_PROJECT_NAME
    GITLAB_PROJECT_ID: $CI_PROJECT_ID
    REPLEXICA_API_KEY: $REPLEXICA_API_KEY
    REPLEXICA_PULL_REQUEST: $REPLEXICA_PULL_REQUEST
    REPLEXICA_COMMIT_MESSAGE: $REPLEXICA_COMMIT_MESSAGE
    REPLEXICA_PULL_REQUEST_TITLE: $REPLEXICA_PULL_REQUEST_TITLE
  script:
    - node build/gitlab.js
