spec:
  inputs:
    api-key:
---
replexica:
  image: node:latest
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0
    REPLEXICA_COMMIT_MESSAGE: "i18n update"
    REPLEXICA_PULL_REQUEST_TITLE: "gitlab can use replexica too"
  script:
    - npx replexica@latest i18n --api-key $[[ inputs.api-key ]]
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
