blank_issues_enabled: false
issue_templates:
  - name: "Bug Report"
    description: "Please fill out the following details to report a bug."
    title: "[BUG] - <title>"
    labels: ["bug"]
    file: "ISSUE_TEMPLATE/bug_report.yml"

  - name: "Feature/Improvement Request"
    description: "Suggest a new feature or improvement for the project."
    title: "[FEATURE] - <title>"
    labels: ["enhancement"]
    file: "ISSUE_TEMPLATE/feature_request.yml"
