import React from "react";

interface SuggestionsPanelProps {
  suggestions: {
    translations?: Array<{
      key: string;
      sourceText: string;
      suggestedText: string;
      targetLanguage: string;
    }>;
    semanticFixes?: Array<{
      key: string;
      issue: string;
      suggestion: string;
    }>;
  } | null;
}

const SuggestionsPanel: React.FC<SuggestionsPanelProps> = ({ suggestions }) => {
  const hasSuggestions =
    suggestions &&
    (suggestions.translations?.length ||
      suggestions.semanticFixes?.length);

  return (
    <section className="card p-4 md:p-5 flex flex-col gap-4 h-full">
      <div>
        <h2 className="text-lg font-semibold text-foreground">
          AI Suggestions
        </h2>
        <p className="text-sm text-muted">
          Intelligent localization improvements generated by Lingo.dev.
        </p>
      </div>
      {!hasSuggestions && (
        <div className="flex flex-1 items-center justify-center text-sm text-muted border border-border rounded-lg bg-surface-muted">
          No AI suggestions yet.
        </div>
      )}
      {hasSuggestions && (
        <div className="flex flex-col gap-4 overflow-auto">
          {suggestions?.translations &&
            suggestions.translations.length > 0 && (
              <SuggestionGroup
                title="Suggested Translations"
                description="Missing or incomplete translations generated using AI."
              >
                {suggestions.translations.map((item, index) => (
                  <TranslationSuggestion
                    key={index}
                    translationKey={item.key}
                    sourceText={item.sourceText}
                    suggestedText={item.suggestedText}
                    targetLanguage={item.targetLanguage}
                  />
                ))}
              </SuggestionGroup>
            )}

          {suggestions?.semanticFixes &&
            suggestions.semanticFixes.length > 0 && (
              <SuggestionGroup
                title="Semantic Improvements"
                description="Suggestions to improve meaning consistency across languages."
              >
                {suggestions.semanticFixes.map((item, index) => (
                  <SemanticSuggestion
                    key={index}
                    translationKey={item.key}
                    issue={item.issue}
                    suggestion={item.suggestion}
                  />
                ))}
              </SuggestionGroup>
            )}
        </div>
      )}
    </section>
  );
};

export default SuggestionsPanel;


interface SuggestionGroupProps {
  title: string;
  description: string;
  children: React.ReactNode;
}

const SuggestionGroup: React.FC<SuggestionGroupProps> = ({
  title,
  description,
  children,
}) => {
  return (
    <div className="flex flex-col gap-2">
      <div>
        <h3 className="text-sm font-medium text-foreground">
          {title}
        </h3>
        <p className="text-xs text-muted">
          {description}
        </p>
      </div>
      <div className="flex flex-col gap-3">{children}</div>
    </div>
  );
};

interface TranslationSuggestionProps {
  translationKey: string;
  sourceText: string;
  suggestedText: string;
  targetLanguage: string;
}

const TranslationSuggestion: React.FC<TranslationSuggestionProps> = ({
  translationKey,
  sourceText,
  suggestedText,
  targetLanguage,
}) => {
  return (
    <div className="rounded-lg border border-border bg-surface-muted p-3">
      <p className="text-sm font-medium text-foreground">
        {translationKey}
      </p>

      <div className="mt-2 space-y-1 text-xs">
        <p className="text-muted">
          <span className="text-subtle">Source:</span> “{sourceText}”
        </p>
        <p className="text-foreground">
          <span className="text-subtle">
            Suggested ({targetLanguage}):
          </span>{" "}
          “{suggestedText}”
        </p>
      </div>

      <div className="mt-2 text-[11px] text-muted">
        Generated by <span className="text-foreground">Lingo.dev</span>
      </div>
    </div>
  );
};

interface SemanticSuggestionProps {
  translationKey: string;
  issue: string;
  suggestion: string;
}

const SemanticSuggestion: React.FC<SemanticSuggestionProps> = ({
  translationKey,
  issue,
  suggestion,
}) => {
  return (
    <div className="rounded-lg border border-border bg-surface-muted p-3">
      <p className="text-sm font-medium text-foreground">
        {translationKey}
      </p>

      <p className="mt-1 text-xs text-warning">
        {issue}
      </p>

      <p className="mt-2 text-xs text-foreground">
        Suggested improvement: {suggestion}
      </p>

      <div className="mt-2 text-[11px] text-muted">
        Generated by <span className="text-foreground">Lingo.dev</span>
      </div>
    </div>
  );
};
