name: Lingo.dev
description: Automated AI localization for dev teams.
author: Lingo.dev

branding:
  icon: "aperture"
  color: "black"

runs:
  using: "composite"
  steps:
    - name: Install pnpm
      run: cd ${{ github.action_path }} && npm install -g pnpm && pnpm install
      shell: bash
    - name: Build
      run: cd ${{ github.action_path }}/action && pnpm build
      shell: bash
    - name: Run
      run: node ${{ github.action_path }}/action/build/index.js
      shell: bash
      env:
        LINGODOTDEV_API_KEY: ${{ inputs.api-key }}
        LINGODOTDEV_PULL_REQUEST: ${{ inputs.pull-request }}
        LINGODOTDEV_COMMIT_MESSAGE: ${{ inputs.commit-message }}
        LINGODOTDEV_PULL_REQUEST_TITLE: ${{ inputs.pull-request-title }}
        LINGODOTDEV_WORKING_DIRECTORY: ${{ inputs.working-directory }}
        LINGODOTDEV_PROCESS_OWN_COMMITS: ${{ inputs.process-own-commits }}
inputs:
  api-key:
    description: "Lingo.dev Platform API Key"
    required: true
  pull-request:
    description: "Create a pull request with the changes"
    default: false
    required: false
  commit-message:
    description: "Commit message"
    required: false
  pull-request-title:
    description: "Pull request title"
    required: false
  working-directory:
    description: "Working directory"
    required: false
  process-own-commits:
    description: "Process commits made by this action"
    required: false
