"use i18n";
import { useState } from "react";
import { Share2, Copy, Check, Twitter, Facebook, Mail, Link2, Download, QrCode } from "lucide-react";
import type { Trip } from "@/store/tripStore";
import { getDestinationById } from "@/data/destinations";
import type { ItineraryItem } from "@/types";

interface ShareTripProps {
  trip: Trip;
}

export default function ShareTrip({ trip }: ShareTripProps) {
  const [copied, setCopied] = useState(false);
  const [showQR, setShowQR] = useState(false);

  const destination = getDestinationById(trip.destinationId);
  
  // Generate shareable text
  const shareText = `Check out my trip to ${destination?.name || trip.destinationId}! ${trip.items.length} activities planned from ${new Date(trip.startDate).toLocaleDateString()} to ${new Date(trip.endDate).toLocaleDateString()}.`;
  
  // Generate a fake shareable URL (in production, this would be a real link)
  const shareUrl = `https://travel-planner.lingo.dev/trip/${trip.id}`;
  
  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(`${shareText}\n\n${shareUrl}`);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };

  const shareToTwitter = () => {
    const url = `https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText)}&url=${encodeURIComponent(shareUrl)}`;
    window.open(url, "_blank");
  };

  const shareToFacebook = () => {
    const url = `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(shareUrl)}&quote=${encodeURIComponent(shareText)}`;
    window.open(url, "_blank");
  };

  const shareByEmail = () => {
    const subject = `My Trip to ${destination?.name || trip.destinationId}`;
    const body = `${shareText}\n\nTrip Details:\n- Destination: ${destination?.name}, ${destination?.country}\n- Dates: ${trip.startDate} to ${trip.endDate}\n- Activities: ${trip.items.length}\n\nView the full itinerary: ${shareUrl}`;
    window.location.href = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  };

  const downloadItinerary = () => {
    // Generate text-based itinerary
    let content = `TRIP ITINERARY\n${"=".repeat(50)}\n\n`;
    content += `Destination: ${destination?.name}, ${destination?.country}\n`;
    content += `Dates: ${trip.startDate} to ${trip.endDate}\n`;
    content += `Travelers: ${trip.travelers}\n`;
    content += `Budget: $${trip.budget} ${trip.currency}\n\n`;
    content += `ACTIVITIES\n${"-".repeat(50)}\n\n`;

    const itemsByDay = trip.items.reduce((acc: Record<number, ItineraryItem[]>, item: ItineraryItem) => {
      if (!acc[item.day]) acc[item.day] = [];
      acc[item.day].push(item);
      return acc;
    }, {} as Record<number, ItineraryItem[]>);

    Object.entries(itemsByDay).forEach(([day, items]) => {
      content += `DAY ${day}\n`;
      (items as ItineraryItem[]).sort((a: ItineraryItem, b: ItineraryItem) => a.time.localeCompare(b.time)).forEach((item: ItineraryItem) => {
        content += `  ${item.time} - ${item.activity}\n`;
        content += `           Location: ${item.location}\n`;
        content += `           Duration: ${item.duration}\n\n`;
      });
    });

    content += `\n${"=".repeat(50)}\n`;
    content += `Generated by AI Travel Planner - Powered by Lingo.dev\n`;

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `trip-to-${destination?.name?.toLowerCase().replace(/\s+/g, "-") || trip.destinationId}-itinerary.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // Simple QR code using a placeholder (in production, use a proper QR library)
  const qrCodeUrl = `https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=${encodeURIComponent(shareUrl)}`;

  return (
    <div className="glass-card p-6 rounded-2xl">
      <h3 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
        <Share2 className="w-5 h-5 text-sky-400" />
        <>Share Your Trip</>
      </h3>

      {/* Trip Preview Card */}
      <div className="mb-6 p-4 rounded-xl bg-gradient-to-br from-sky-500/10 to-violet-500/10 border border-white/10">
        <div className="flex gap-4">
          {destination && (
            <img
              src={destination.imageUrl}
              alt={destination.name}
              className="w-20 h-20 rounded-lg object-cover"
            />
          )}
          <div>
            <h4 className="font-semibold text-white">{trip.name}</h4>
            <p className="text-sm text-gray-400">{destination?.name}, {destination?.country}</p>
            <p className="text-xs text-gray-500 mt-1">
              {new Date(trip.startDate).toLocaleDateString()} - {new Date(trip.endDate).toLocaleDateString()}
            </p>
            <p className="text-xs text-sky-400 mt-1">{trip.items.length} <>activities planned</></p>
          </div>
        </div>
      </div>

      {/* Share Buttons */}
      <div className="grid grid-cols-2 gap-3 mb-4">
        <button
          onClick={shareToTwitter}
          className="flex items-center justify-center gap-2 p-3 rounded-xl bg-[#1DA1F2]/20 hover:bg-[#1DA1F2]/30 text-[#1DA1F2] transition-colors"
        >
          <Twitter className="w-5 h-5" />
          <span className="text-sm font-medium">Twitter</span>
        </button>
        <button
          onClick={shareToFacebook}
          className="flex items-center justify-center gap-2 p-3 rounded-xl bg-[#4267B2]/20 hover:bg-[#4267B2]/30 text-[#4267B2] transition-colors"
        >
          <Facebook className="w-5 h-5" />
          <span className="text-sm font-medium">Facebook</span>
        </button>
        <button
          onClick={shareByEmail}
          className="flex items-center justify-center gap-2 p-3 rounded-xl bg-emerald-500/20 hover:bg-emerald-500/30 text-emerald-400 transition-colors"
        >
          <Mail className="w-5 h-5" />
          <span className="text-sm font-medium">Email</span>
        </button>
        <button
          onClick={() => setShowQR(!showQR)}
          className="flex items-center justify-center gap-2 p-3 rounded-xl bg-violet-500/20 hover:bg-violet-500/30 text-violet-400 transition-colors"
        >
          <QrCode className="w-5 h-5" />
          <span className="text-sm font-medium">QR Code</span>
        </button>
      </div>

      {/* QR Code */}
      {showQR && (
        <div className="mb-4 p-4 bg-white rounded-xl flex justify-center">
          <img src={qrCodeUrl} alt="QR Code" className="w-40 h-40" />
        </div>
      )}

      {/* Copy Link */}
      <div className="flex gap-2 mb-4">
        <div className="flex-1 flex items-center gap-2 px-3 py-2 rounded-lg bg-white/5 text-sm text-gray-400 overflow-hidden">
          <Link2 className="w-4 h-4 flex-shrink-0" />
          <span className="truncate">{shareUrl}</span>
        </div>
        <button
          onClick={copyToClipboard}
          className={`px-4 py-2 rounded-lg flex items-center gap-2 transition-all ${
            copied
              ? "bg-emerald-500 text-white"
              : "bg-white/10 hover:bg-white/20 text-white"
          }`}
        >
          {copied ? (
            <>
              <Check className="w-4 h-4" />
              <span className="text-sm"><>Copied!</></span>
            </>
          ) : (
            <>
              <Copy className="w-4 h-4" />
              <span className="text-sm"><>Copy</></span>
            </>
          )}
        </button>
      </div>

      {/* Download */}
      <button
        onClick={downloadItinerary}
        className="w-full flex items-center justify-center gap-2 p-3 rounded-xl bg-white/5 hover:bg-white/10 text-gray-300 transition-colors"
      >
        <Download className="w-5 h-5" />
        <span className="text-sm font-medium"><>Download Itinerary</></span>
      </button>
    </div>
  );
}
