version: "3"
services:
  directus:
    build:
      context: ./
    ports:
      - 8055:8055
    volumes:
      - ./.directus/database:/directus/database
      - ./.directus/uploads:/directus/uploads
      - ./:/directus/extensions/lingo.dev-directus-extension
    environment:
      SECRET: "replace-with-secure-random-value"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "true"
