name: 🐛 Bug Report
description: Report a bug with detailed reproduction steps
labels: ["Bug"]
body:
  - type: markdown
    attributes:
      value: |
        **Reproducibility is critical.** Provide exact steps so maintainers can reproduce instantly.

  - type: textarea
    id: description
    attributes:
      label: What's happening?
      placeholder: Describe the bug in 1-2 sentences
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Exact Reproduction Steps
      description: Must be copy-pasteable commands/actions
      placeholder: |
        1. `npx lingo.dev init` (exact command)
        2. Edit `lingo.config.json`: [exact change]
        3. `npx lingo.dev ci` (exact command)
        4. Error appears: [exact error message]
      value: |
        1.
        2.
        3.
        4.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected
      placeholder: Should show X / Should execute Y
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual
      placeholder: Shows error Z / Crashes with message W
    validations:
      required: true

  - type: textarea
    id: visuals
    attributes:
      label: Screenshots/Videos
      description: "**REQUIRED** - Drag and drop images/videos here"
      placeholder: |
        Attach:
        - Screenshot of error
        - Terminal output (full)
        - Video of bug happening (if interaction-based)
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS
      placeholder: "macOS 14.2 / Windows 11 / Ubuntu 22.04"
    validations:
      required: true

  - type: input
    id: node
    attributes:
      label: Node.js
      placeholder: "20.17.0 (run: node --version)"
    validations:
      required: true

  - type: input
    id: lingo_version
    attributes:
      label: lingo.dev
      placeholder: "0.114.0 (run: npx lingo.dev --version)"
    validations:
      required: true

  - type: input
    id: terminal
    attributes:
      label: Terminal
      placeholder: "Bash / PowerShell / Zsh / GitBash"
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Paste your `lingo.config.json` (remove sensitive keys)
      placeholder: |
        ```json
        {
          "provider": { ... }
        }
        ```
