name: "Documentation Issue"
description: "Report an issue or suggest an improvement for the documentation."
labels: [documentation]
body:
  - type: markdown
    attributes:
      value: |
        ## Documentation Issue
        Please provide details about the documentation problem or improvement.
  - type: textarea
    id: section
    attributes:
      label: Section / Page
      description: "Which page or section of the documentation does this relate to?"
      placeholder: "e.g. Getting Started / Installation / API Reference"
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem / Issue
      description: "Describe the documentation issue or what is unclear."
      placeholder: "Explain what is missing, incorrect, or confusing."
    validations:
      required: true
  - type: textarea
    id: suggested_fix
    attributes:
      label: Suggested Fix / Improvement
      description: "Provide a suggested fix, clarification, or improvement for the documentation."
      placeholder: "Describe how the documentation could be improved."
  - type: textarea
    id: examples
    attributes:
      label: Examples / References
      description: "Provide examples, links, or references if applicable."
  - type: input
    id: version
    attributes:
      label: Version / Branch
      description: "Specify the version or branch of the project the docs relate to."
      placeholder: "e.g. v2.1.0, main branch"
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: "Any other context or comments regarding this documentation issue."
