"use client";

import { motion } from "framer-motion";
import { useLingoContext } from "@lingo.dev/compiler/react";
import { useRouter, usePathname } from "next/navigation";

const languages = [
  { code: "en", name: "English", hello: "Hello", flag: "🇺🇸" },
  { code: "es", name: "Spanish", hello: "Hola", flag: "🇪🇸" },
  { code: "fr", name: "French", hello: "Bonjour", flag: "🇫🇷" },
  { code: "de", name: "German", hello: "Hallo", flag: "🇩🇪" },
  { code: "ja", name: "Japanese", hello: "こんにちは", flag: "🇯🇵" },
  { code: "zh", name: "Chinese", hello: "你好", flag: "🇨🇳" },
  { code: "ko", name: "Korean", hello: "안녕하세요", flag: "🇰🇷" },
  { code: "ar", name: "Arabic", hello: "مرحبا", flag: "🇸🇦" },
  { code: "hi", name: "Hindi", hello: "नमस्ते", flag: "🇮🇳" },
  { code: "pt", name: "Portuguese", hello: "Olá", flag: "🇧🇷" },
  { code: "ru", name: "Russian", hello: "Привет", flag: "🇷🇺" },
];

export function LanguageGrid() {
  const { locale: currentLocale } = useLingoContext();
  const router = useRouter();
  const pathname = usePathname();

  const handleLocaleChange = (localeCode: string) => {
    const segments = pathname.split("/");
    segments[1] = localeCode;
    router.push(segments.join("/"));
  };

  return (
    <section className="py-32 px-8 md:px-12 lg:px-16">
      <div className="max-w-6xl mx-auto w-full">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <h2 className="text-4xl md:text-5xl font-bold mb-4">
            <span className="gradient-text">11 Languages</span>, One Click
          </h2>
          <p className="text-xl text-gray-400 max-w-2xl mx-auto">
            Click any language below and watch the entire page transform.
            Every piece of text you are reading right now will be translated.
          </p>
        </motion.div>

        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-4">
          {languages.map((lang, index) => {
            const isActive = currentLocale === lang.code;

            return (
              <motion.div
                key={lang.code}
                initial={{ opacity: 0, scale: 0.8 }}
                whileInView={{ opacity: 1, scale: 1 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.05 }}
              >
                <button
                  onClick={() => handleLocaleChange(lang.code)}
                  className={`
                    w-full glass rounded-2xl p-6 flex flex-col items-center gap-3
                    transition-all hover:scale-105 group cursor-pointer
                    ${isActive
                      ? "bg-gradient-to-r from-purple-600/30 to-cyan-600/30 glow-purple"
                      : "hover:bg-white/10 hover:glow-purple"
                    }
                  `}
                >
                  <span className="text-4xl group-hover:scale-125 transition-transform">
                    {lang.flag}
                  </span>
                  <span className="text-2xl font-bold text-white">{lang.hello}</span>
                  <span className="text-sm text-gray-400">{lang.name}</span>
                </button>
              </motion.div>
            );
          })}
        </div>

        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          className="mt-12 text-center"
        >
          <p className="text-gray-500 text-sm">
            All translations are generated by AI during the build process.
            No manual translation files needed.
          </p>
        </motion.div>
      </div>
    </section>
  );
}
