import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { LingoProvider } from "@lingo.dev/compiler/react/next";
import type { ReactNode } from "react";
import type { LocaleCode } from "@lingo.dev/compiler";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: Readonly<{
  children: ReactNode;
  params: Promise<{ locale: LocaleCode }>;
}>) {
  const { locale } = await params;

  console.debug("LocaleLayout", { locale });
  return (
    <LingoProvider initialLocale={locale}>
      <html lang={locale}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </LingoProvider>
  );
}
