
// This file is auto-generated by LingoLaunch to enable dynamic content translation.
// Do not edit manually.
import { useLingo } from '@lingo.dev/compiler/react';

export default function LingoDynamicSource() {
  const { t } = useLingo();
  
  return (
    <>
      {/* @ts-ignore */}
      {t("Pricing page")}
      {/* @ts-ignore */}
      {t("Here are the prices for using this application its 1000 rs one time payment")}
      {/* @ts-ignore */}
      {t("Welcome to Our Page")}
      {/* @ts-ignore */}
      {t("Discover what we have to offer")}
      {/* @ts-ignore */}
      {t("Learn More")}
      {/* @ts-ignore */}
      {t("Our Features")}
      {/* @ts-ignore */}
      {t("Fast Performance")}
      {/* @ts-ignore */}
      {t("Lightning quick load times for every visitor.")}
      {/* @ts-ignore */}
      {t("Easy to Use")}
      {/* @ts-ignore */}
      {t("Intuitive interface that anyone can master.")}
      {/* @ts-ignore */}
      {t("Reliable")}
      {/* @ts-ignore */}
      {t("Built to scale with your growing business.")}
      {/* @ts-ignore */}
      {t("About Us")}
      {/* @ts-ignore */}
      {t("Tell your story here. Share what makes your product or service unique and why customers should choose you.")}
      {/* @ts-ignore */}
      {t("Ready to Get Started?")}
      {/* @ts-ignore */}
      {t("Take the next step and join thousands of satisfied customers.")}
      {/* @ts-ignore */}
      {t("Sign Up Now")}
      {/* @ts-ignore */}
      {t("This product completely transformed how we do business. Highly recommended!")}
      {/* @ts-ignore */}
      {t("Jane Doe")}
      {/* @ts-ignore */}
      {t("CEO at TechCorp")}
    </>
  );
}
