import type { Metadata } from "next";

import { LocaleSwitcher } from "lingo.dev/react/client";
import { LingoProvider, loadDictionary } from "lingo.dev/react/rsc";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <LingoProvider loadDictionary={(locale) => loadDictionary(locale)}>
      <div id="switcher">
        <LocaleSwitcher locales={["en", "es", "fr"]} />
      </div>
      {children}
    </LingoProvider>
  );
}
