name: Build Docker Image

on:
  workflow_dispatch:
  push:
    paths:
      - Dockerfile
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64
          context: ./
          file: ./Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ci-action:latest
