name: Generate CLI Docs

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "packages/cli/**"
      - "scripts/docs/src/generate-cli-docs.ts"
      - "scripts/docs/package.json"

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.12.2

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
          version: 9.12.3
          run_install: false

      - name: Configure pnpm cache
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install deps
        run: pnpm install

      - name: Setup
        run: |
          pnpm turbo telemetry disable

      - name: Configure Turbo cache
        uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: Build
        run: pnpm turbo build --force

      - name: Generate CLI docs
        run: pnpm --filter docs run generate-cli-docs

      - name: Commit and push changes (if any)
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "docs: update CLI command reference [skip ci]"
          add: "docs/cli-commands.md"
