name: "Lingo.dev"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Lingo.dev CLI version"
        default: "latest"
        required: false
      pull-request:
        description: "Create a pull request with the changes"
        type: boolean
        default: false
        required: false
      commit-message:
        description: "Commit message"
        default: "feat: update translations via @LingoDotDev"
        required: false
      pull-request-title:
        description: "Pull request title"
        default: "feat: update translations via @LingoDotDev"
        required: false
      working-directory:
        description: "Working directory"
        default: "."
        required: false
      process-own-commits:
        description: "Process commits made by this action"
        type: boolean
        default: false
        required: false
      parallel:
        description: "Run in parallel mode"
        type: boolean
        default: false
        required: false

jobs:
  lingodotdev:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Lingo.dev
        uses: ./
        with:
          api-key: ${{ secrets.LINGODOTDEV_API_KEY }}
          version: ${{ inputs.version }}
          pull-request: ${{ inputs['pull-request'] }}
          commit-message: ${{ inputs['commit-message'] }}
          pull-request-title: ${{ inputs['pull-request-title'] }}
          working-directory: ${{ inputs['working-directory'] }}
          process-own-commits: ${{ inputs['process-own-commits'] }}
          parallel: ${{ inputs.parallel }}
        env:
          GH_TOKEN: ${{ github.token }}
