name: Check PR

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.sha}}
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.11.0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
          version: 9.1.1
          run_install: false

      - name: Configure pnpm cache
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Replexica
        uses: ./
        with:
          api-key: ${{ secrets.REPLEXICA_API_KEY }}

      - name: Install deps
        run: pnpm install

      - name: Setup
        run: |
          pnpm turbo telemetry disable

      - name: Configure Turbo cache
        uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: Build
        run: pnpm turbo build --force
        
      - name: Test
        run: pnpm turbo test --force

      - name: Require changeset to be present in PR
        if: github.event.pull_request.user.login != 'dependabot[bot]'
        run: pnpm changeset status --since origin/main
