name: Publish PHP SDK to Packagist

on:
  push:
    branches:
      - main
    paths:
      - 'php/sdk/**'
  release:
    types: [created]
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Check for PHP SDK changes
        id: check_changes
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q "^php/sdk/"; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Get current version
        if: steps.check_changes.outputs.changes == 'true'
        id: current_version
        run: |
          VERSION=$(node -p "require('./php/sdk/package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Bump version
        if: steps.check_changes.outputs.changes == 'true'
        id: bump_version
        run: |
          # Extract version components
          MAJOR=$(echo ${{ steps.current_version.outputs.version }} | cut -d. -f1)
          MINOR=$(echo ${{ steps.current_version.outputs.version }} | cut -d. -f2)
          PATCH=$(echo ${{ steps.current_version.outputs.version }} | cut -d. -f3)
          
          # Check for changeset type
          if grep -q "\"@lingo.dev/php-sdk\": major" .changeset/*.md 2>/dev/null; then
            NEW_VERSION="$((MAJOR+1)).0.0"
          elif grep -q "\"@lingo.dev/php-sdk\": minor" .changeset/*.md 2>/dev/null; then
            NEW_VERSION="$MAJOR.$((MINOR+1)).0"
          else
            NEW_VERSION="$MAJOR.$MINOR.$((PATCH+1))"
          fi
          
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          
          # Update version in package.json
          node -e "const fs=require('fs');const pkg=require('./php/sdk/package.json');pkg.version='$NEW_VERSION';fs.writeFileSync('./php/sdk/package.json',JSON.stringify(pkg,null,2));"
          
          # Update version in composer.json
          node -e "const fs=require('fs');const pkg=JSON.parse(fs.readFileSync('./php/sdk/composer.json'));pkg.version='$NEW_VERSION';fs.writeFileSync('./php/sdk/composer.json',JSON.stringify(pkg,null,2));"

      - name: Commit version bump
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "devin-ai-integration[bot]@users.noreply.github.com"
          git config --local user.name "Devin AI"
          git add php/sdk/package.json php/sdk/composer.json
          git commit -m "chore: bump PHP SDK version to ${{ steps.bump_version.outputs.new_version }}"
          git push

  publish:
    runs-on: ubuntu-latest
    needs: version
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'release' && contains(github.ref, 'refs/tags/')) ||
      github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, intl
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: |
          cd php/sdk
          composer install --no-dev --no-interaction --prefer-dist

      - name: Update Packagist
        run: |
          curl -XPOST -H "content-type:application/json" \
          "https://packagist.org/api/update-package?username=lingodotdev&apiToken=${{ secrets.PACKAGIST_API_TOKEN }}" \
          -d '{"repository":{"url":"https://github.com/lingodotdev/lingo.dev"}}'
