name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write # Required for npm Trusted Publishing with OIDC
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug Permissions
        run: |
          ls -la
          ls -la integrations/
          ls -la integrations/directus/

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Upgrade npm for OIDC support
        run: npm install -g npm@11.5.1

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
          version: 11.10.0
          run_install: false

      - name: Configure pnpm cache
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install deps
        run: pnpm install

      - name: Setup
        run: |
          pnpm turbo telemetry disable

      - name: Configure Turbo cache
        uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: Build
        run: pnpm turbo build --force

      - name: Test
        run: pnpm turbo test --force

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GHA_BOT_GPG }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v2
        with:
          pr-title: "chore: bump package versions"
          version-script: pnpm changeset version
          publish-script: pnpm changeset publish
          commit-message: "chore: bump package version"
          push-with-git-cli: true
        env:
          NPM_CONFIG_PROVENANCE: true
