import { useState } from 'react';
import { FileCode, Check } from 'lucide-react';
import type { Metadata, TranslationResult } from '../services/api';

interface CombinedDataDownloadProps {
  selectedLanguages: string[];
  metadata: Metadata | null;
  translations: TranslationResult;
}

// Language mapping: Display name -> Language code
const LANGUAGE_CODE_MAP: Record<string, string> = {
  English: "en",
  Spanish: "es",
  French: "fr",
  German: "de",
  Japanese: "ja",
  Chinese: "zh",
  Portuguese: "pt",
  Italian: "it",
  Russian: "ru",
  Ukrainian: "uk",
  Belarusian: "be",
  Hindi: "hi",
  Arabic: "ar",
  Bulgarian: "bg",
  Czech: "cs",
  Welsh: "cy",
  Dutch: "nl",
  Polish: "pl",
  Indonesian: "id",
  Icelandic: "is",
  Malay: "ms",
  Finnish: "fi",
  Basque: "eu",
  Croatian: "hr",
  Hebrew: "he",
  Khmer: "km",
  Latvian: "lv",
  Lithuanian: "lt",
  Norwegian: "no",
  Korean: "ko",
  Urdu: "ur",
  Vietnamese: "vi",
  Turkish: "tr",
  Tamil: "ta",
  Serbian: "sr",
  Hungarian: "hu",
  Estonian: "et",
  Greek: "el",
  Danish: "da",
  Azerbaijani: "az",
  Thai: "th",
  Swedish: "sv",
  Catalan: "ca",
  Kazakh: "kk",
  Romanian: "ro",
  Slovak: "sk",
  Swahili: "sw",
  Persian: "fa",
  Punjabi: "pa",
  Bengali: "bn",
  Irish: "ga",
  Galician: "gl",
  Maltese: "mt",
  Slovenian: "sl",
  Albanian: "sq",
  Afrikaans: "af",
  Uzbek: "uz",
  Somali: "so",
  Tigrinya: "ti",
  Tagalog: "tl",
  Telugu: "te",
  Kinyarwanda: "rw",
  Georgian: "ka",
  Malayalam: "ml",
  Armenian: "hy",
  Macedonian: "mk",
};

export function CombinedDataDownload({ selectedLanguages, metadata, translations }: CombinedDataDownloadProps) {
  const [downloaded, setDownloaded] = useState(false);

  const generateCombinedHTML = () => {
    if (!metadata) return '';

    let combinedHTML = `<!-- 
  SEO-Optimized Metadata for Multiple Languages
  Generated by GlobSEO
  
  Instructions:
  1. Copy this entire block
  2. Paste it in the <head> section of your HTML
  3. The hreflang tags will help search engines serve the right language
  4. Each language has its own meta tags with proper lang attributes
-->

`;

    // Add hreflang links for all languages
    combinedHTML += `<!-- Hreflang tags for multi-language support -->\n`;
    selectedLanguages.forEach((language) => {
      const langCode = LANGUAGE_CODE_MAP[language] || language.toLowerCase();
      const url = metadata.url || metadata.canonical || '';
      const languageUrl = langCode === 'en' ? url : `${url}/${langCode}`;
      combinedHTML += `<link rel="alternate" hreflang="${langCode}" href="${languageUrl}" />\n`;
    });
    combinedHTML += `<link rel="alternate" hreflang="x-default" href="${metadata.url || metadata.canonical || ''}" />\n\n`;

    // Generate metadata for each language
    selectedLanguages.forEach((language) => {
      const langCode = LANGUAGE_CODE_MAP[language] || language.toLowerCase();
      const isEnglish = language === 'English';
      const translatedData = translations[langCode];

      // Get metadata values
      const getMetadataValue = (field: 'title' | 'description' | 'keywords' | 'ogTitle' | 'ogDescription' | 'h1') => {
        if (isEnglish && metadata) {
          return metadata[field] || '';
        }
        
        if (translatedData) {
          if (field === 'title' || field === 'description' || field === 'keywords' || field === 'h1') {
            return translatedData.meta?.[field] || '';
          }
          if (field === 'ogTitle') {
            return translatedData.og?.title || '';
          }
          if (field === 'ogDescription') {
            return translatedData.og?.description || '';
          }
        }
        
        return metadata?.[field] || '';
      };

      const title = getMetadataValue('title');
      const description = getMetadataValue('description');
      const keywords = getMetadataValue('keywords');
      const ogTitle = getMetadataValue('ogTitle') || title;
      const ogDescription = getMetadataValue('ogDescription') || description;
      const ogImage = metadata?.ogImage || '';
      const url = metadata?.url || metadata?.canonical || '';

      combinedHTML += `<!-- ========================================
   ${language} (${langCode}) Metadata
   ======================================== -->\n`;
      
      // Basic meta tags
      combinedHTML += `<meta name="description" content="${description}" lang="${langCode}" />\n`;
      combinedHTML += `<meta name="keywords" content="${keywords}" lang="${langCode}" />\n\n`;

      // Open Graph tags
      combinedHTML += `<!-- Open Graph / Facebook -->\n`;
      combinedHTML += `<meta property="og:type" content="website" />\n`;
      combinedHTML += `<meta property="og:url" content="${url}" />\n`;
      combinedHTML += `<meta property="og:title" content="${ogTitle}" />\n`;
      combinedHTML += `<meta property="og:description" content="${ogDescription}" />\n`;
      if (ogImage) {
        combinedHTML += `<meta property="og:image" content="${ogImage}" />\n`;
      }
      combinedHTML += `<meta property="og:locale" content="${langCode === 'en' ? 'en_US' : langCode + '_' + langCode.toUpperCase()}" />\n\n`;

      // Twitter Card tags
      combinedHTML += `<!-- Twitter -->\n`;
      combinedHTML += `<meta property="twitter:card" content="summary_large_image" />\n`;
      combinedHTML += `<meta property="twitter:url" content="${url}" />\n`;
      combinedHTML += `<meta property="twitter:title" content="${title}" />\n`;
      combinedHTML += `<meta property="twitter:description" content="${description}" />\n`;
      if (ogImage) {
        combinedHTML += `<meta property="twitter:image" content="${ogImage}" />\n`;
      }
      combinedHTML += `\n`;

      // Schema.org JSON-LD
      const schemaMarkup = {
        "@context": "https://schema.org",
        "@type": "WebPage",
        "name": title,
        "description": description,
        "url": url,
        "inLanguage": langCode,
        ...(ogImage && { "image": ogImage }),
        ...(keywords && { "keywords": keywords })
      };

      combinedHTML += `<!-- Schema.org JSON-LD for ${language} -->\n`;
      combinedHTML += `<script type="application/ld+json">\n${JSON.stringify(schemaMarkup, null, 2)}\n</script>\n\n`;
    });

    return combinedHTML;
  };

  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const handleDownload = () => {
    const htmlContent = generateCombinedHTML();
    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `seo-metadata-all-languages-${new Date().toISOString().split('T')[0]}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    setDownloaded(true);
    setTimeout(() => setDownloaded(false), 3000);
  };

  const handleCopy = () => {
    const htmlContent = generateCombinedHTML();
    navigator.clipboard.writeText(htmlContent);
    setDownloaded(true);
    setTimeout(() => setDownloaded(false), 3000);
  };

  return (
    <div className="bg-gradient-to-br from-[#141414] to-[#0f0f0f] border border-white/10 rounded-xl p-6 relative overflow-hidden">
      {/* Background gradient */}
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_120%,rgba(163,255,18,0.1),transparent_50%)]"></div>
      
      <div className="relative z-10">
        <div className="flex items-start justify-between mb-6">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-[#a3ff12]/10 rounded-lg">
              <FileCode className="w-5 h-5 text-[#a3ff12]" />
            </div>
            <div>
              <h4 className="text-white/90 font-semibold">Combined HTML Export</h4>
              <p className="text-white/40 text-sm">
                All {selectedLanguages.length} language{selectedLanguages.length !== 1 ? 's' : ''} with complete SEO metadata
              </p>
            </div>
          </div>
        </div>

        {/* Two Column Layout */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* Left Column - Feature List */}
          <div className="bg-black/20 rounded-lg p-4 border border-white/5">
            <div className="space-y-2 text-sm">
              <div className="flex items-center gap-2 text-white/60">
                <span className="w-1.5 h-1.5 rounded-full bg-[#a3ff12]"></span>
                <span>HTML Meta Tags (title, description, keywords)</span>
              </div>
              <div className="flex items-center gap-2 text-white/60">
                <span className="w-1.5 h-1.5 rounded-full bg-[#a3ff12]"></span>
                <span>Open Graph Tags (Facebook, LinkedIn)</span>
              </div>
              <div className="flex items-center gap-2 text-white/60">
                <span className="w-1.5 h-1.5 rounded-full bg-[#a3ff12]"></span>
                <span>Twitter Card Metadata</span>
              </div>
              <div className="flex items-center gap-2 text-white/60">
                <span className="w-1.5 h-1.5 rounded-full bg-[#a3ff12]"></span>
                <span>Schema.org JSON-LD for each language</span>
              </div>
              <div className="flex items-center gap-2 text-white/60">
                <span className="w-1.5 h-1.5 rounded-full bg-[#a3ff12]"></span>
                <span>Hreflang tags for multi-language support</span>
              </div>
            </div>
          </div>

          {/* Right Column - Buttons and Tip */}
          <div className="flex flex-col gap-4 justify-center items-center">
            <button
              onClick={handleCopy}
              className="w-1/2 bg-white/5 hover:bg-white/10 text-white font-semibold py-3 px-4 rounded-lg transition-all flex items-center justify-center gap-2 hover:scale-105 active:scale-95 border border-white/10 cursor-pointer"
            >
              {downloaded ? (
                <>
                  <Check className="w-4 h-4" />
                  Copied!
                </>
              ) : (
                <>
                  <FileCode className="w-4 h-4" />
                  Copy Code
                </>
              )}
            </button>

            <div className="p-3 bg-[#a3ff12]/5 rounded-lg border border-[#a3ff12]/20">
              <p className="text-sm text-white/60">
                💡 <span className="font-semibold text-white/80">Tip:</span> Paste this code in the <code className="text-[#a3ff12] bg-black/30 px-1.5 py-0.5 rounded">&lt;head&gt;</code> section of your HTML to optimize your website for search engines across all languages.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
